### PR TITLE
Fixing issue #1

### PR DESCRIPTION
**Pull request by Mibou**
Fixing issue #1 for compatibility with Django 1.8 .
Fixing the broken PEP8 .

### CODE REVIEW

**Comment by horva** [comment]
@mjtamlyn Hi, can you pleaase merge this and update on PyPI?

**Comment by kevinetienne** [comment]
Looks good, sounds like `add_to_query` would be deprecated in [Django 1.10](https://github.com/django/django/blob/d58a324bea2df202bc09bd887f564c3f8e35b2ec/django/db/models/aggregates.py#L40-L58)

**Comment by kevinetienne** [comment]
Released under [`0.2`](https://pypi.python.org/pypi/django-boolean-sum)

**Comment by mjtamlyn** [comment]
Yeah this should be reimplemented using `as_postgresql` now I think.

**Pull request merged**
